import { AdditionalService } from '@/types/booking';

export const ADDITIONAL_SERVICES: AdditionalService[] = [
    {
        id: 'conductor-privado',
        name: 'Conductor Privado',
        description: 'Chofer profesional con experiencia en rutas costeras y los mejores destinos turísticos de la región Piura.',
        pricePerDay: 120,
        icon: 'UserCheck',
        isPopular: true,
        isIncluded: false,
    },
    {
        id: 'seguro-adicional',
        name: 'Seguro Adicional',
        description: 'Cobertura extendida contra daños, robo y responsabilidad civil. Tranquilidad total durante tu viaje.',
        pricePerDay: 35,
        icon: 'Shield',
        isPopular: true,
        isIncluded: false,
    },
    {
        id: 'asistencia-24-7',
        name: 'Asistencia 24/7',
        description: 'Soporte técnico y asistencia en carretera disponible las 24 horas durante todo tu recorrido.',
        pricePerDay: 25,
        icon: 'Headphones',
        isPopular: true,
        isIncluded: false,
    },
    {
        id: 'entrega-aeropuerto',
        name: 'Entrega en Aeropuerto',
        description: 'Entrega directa en el aeropuerto de Piura. Tu vehículo te estará esperando para que empieces tu viaje o ruta de negocios sin demoras.',
        pricePerDay: 50,
        icon: 'Plane',
        isPopular: false,
        isIncluded: false,
    },
    {
        id: 'gps-navegador',
        name: 'GPS / Navegador',
        description: 'Navegador GPS configurado con mapas detallados de la costa norte, sus playas y las rutas comerciales más importantes.',
        pricePerDay: 15,
        icon: 'MapPin',
        isPopular: false,
        isIncluded: false,
    },
    {
        id: 'silla-bebe',
        name: 'Silla para Bebé',
        description: 'Silla de seguridad homologada para niños de 0 a 4 años. Tu familia viaja segura.',
        pricePerDay: 20,
        icon: 'Baby',
        isPopular: false,
        isIncluded: false,
    },
];
